FORMAT: 1A
HOST: http://app.apiary.io/majesticthai17

# MajesticThai



## Menu Collection [/dishes]

### List of Menu Items [GET]

+ Response 200 (application/json)

        [
            {
                "dishes": [
                  {
                    'id': '01', 
                    'name': 'Pad Thai', 
                    'description': 'yummy yummy yummy for your tummy tummy tummy', 
                    'price': '820'
                  },
                  {
                    'id': '02', 
                    'name': 'Pineapple Fried Rice', 
                    'description': 'sure it’ fattening but it tastes sooooo good!', 
                    'price': '925'
                  },
                  {
                      'id': '03', 
                      'name': 'Thai Nee Dish', 
                      'description': 'not much for you to eat but it is spicy to keep remembering long time', 
                      'price': '795'
                  }
                ]
            }
        ]

## Orders Collection [/orders]

### List of Orders [GET]

+ Response 200 (application/json)

        [
            {
                "orders": [
                  {
                    'id': '01', 
                    'username': 'Tommy Tutone', 
                    'order-time': '2016-02-05T08:40:51.620Z', 
                    'order-total': '1220',
                    'order-items': ['Pad Thai', 'Pineapple Fried Rice', 'Sprite']
                  },
                  {
                    'id': '02', 
                    'username': 'Charlie Brown', 
                    'order-time': '2016-02-05T08:43:22.620Z', 
                    'order-total': '1150',
                    'order-items': ['Pineapple Fried Rice', 'Iced Tea']
                  },
                  {
                    'id': '03', 
                    'username': 'Hillary Clinton', 
                    'order-time': '2016-02-05T08:49:40.620Z', 
                    'order-total': '1430',
                    'order-items': ['Thai Nee Dish', 'Pad Thai', 'Thai Beer']
                  }
                ]
            }
        ]